translations = {

    # =====================================================
    # GLOBAL
    # =====================================================

    "dashboard": "Dashboard",
    "jobs": "Jobs",
    "talent_pool": "Talent Pool",
    "search": "Search Talent",
    "history": "History",
    "clients": "Clients",
    "logout": "Sign out",

    "upload_resume": "Upload Resume",
    "upload_resumes": "Upload Resumes",
    "professional_profile": "Professional Profile",
    "professional_summary": "Professional Summary",
    "ai_professional_summary": "AI Professional Summary",
    "skills": "Main Skills",
    "email": "Email",
    "phone": "Phone",
    "view_resume": "View Resume",
    "whatsapp": "WhatsApp",
    "language": "Language",
    "recruiter_notes": "Recruiter's Notes",
    "years_experience": "Experience",
    "location": "Location",
    "ai_match": "AI Match",

    # =====================================================
    # DASHBOARD HEADER
    # =====================================================

    "dashboard_title": "Talent Intelligence Dashboard",
    "dashboard_description":
        "Track recruitment metrics, jobs and performance in real time.",
    "new_job": "+ New Job",

    # =====================================================
    # EXECUTIVE METRICS
    # =====================================================

    "active_jobs": "Active Jobs",
    "open_positions": "Open positions",
    "new_today": "new today",

    "internal_database": "Internal database",
    "total_registered_candidates": "Total registered candidates",

    "interviews": "Interviews",
    "scheduled_today": "Scheduled today",
    "recruitment_agenda": "Recruitment agenda",

    "match_90": "Match >= 90%",
    "ready_to_submit": "Ready to submit",
    "high_confidence_candidates": "High confidence candidates",

    # =====================================================
    # RECRUITMENT PIPELINE
    # =====================================================

    "recruitment_pipeline": "Recruitment Pipeline",
    "pipeline_description":
        "Track every stage of your hiring process.",

    "candidates": "Candidates",
    "applications": "Applications",
    "screening": "Screening",
    "technical_interview": "Technical Interview",
    "client_interview": "Client Interview",
    "offer": "Offer",
    "hired": "Hired",

    # =====================================================
    # TALIA
    # =====================================================

    "executive_recruitment_intelligence":
        "Executive Recruitment Intelligence",

    "ai_active": "AI ACTIVE",
    "top_matches": "Top Matches",
    "avg_match": "Avg Match",
    "executive_insights": "Executive Insights",
    "ai_recommendation": "AI Recommendation",
    "search_talent": "Search Talent",
    "view_talent_pool": "View Talent Pool",

    # =====================================================
    # JOBS / TALENT ACQUISITION WORKSPACE
    # =====================================================

    "back_to_dashboard": "Back to Dashboard",
    "talent_acquisition": "TALENT ACQUISITION",

    "jobs_workspace_title": "Talent Acquisition Workspace",
    "jobs_workspace_description":
        "Manage jobs, candidates and recruitment processes in one place.",

    "search_jobs_placeholder":
        "Search by ID, job or client...",

    "generate_ai_announcement": "Generate AI Announcement",

    "available_candidates": "Available Candidates",
    "ai_announcements": "AI Announcements",
    "ai_announcement_generated": "AI-generated Announcement",
    "back_to_job": "Back to Job",
    "generated_by_talia": "Generated by TALIA",
    "average_match": "Average Match",
    "ai_intelligence": "AI Intelligence",

    "active_recruitment_processes":
        "active recruitment processes",

    "active_status": "Active",
    "created_at": "Created at",
    "open_workspace": "Open Workspace",

    "untitled_job": "Untitled",
    "client_not_informed": "Client not informed",

    "no_jobs_registered": "No jobs registered",
    "no_jobs_registered_description":
        "Click New Job to create your first recruitment process.",

    "no_jobs_found": "No jobs found",
    "no_jobs_found_description":
        "Try searching by another ID, job title or client.",

    # =====================================================
    # NEW JOB
    # =====================================================

    "new_job_title": "New Job",
    "job_title": "Job title",
    "select_client": "Select a client",
    "keywords": "Keywords",
    "keywords_placeholder": "Ex: sap sd*, s4hana*, otc, english",
    "required_skills_help": "Use * for required skills.",
    "weighted_skills_help": "Skills marked with * have more weight in the match.",
    "status": "Status",
    "open_status": "Open",
    "closed_status": "Closed",
    "save_job": "Save job",

    # =====================================================
    # SEARCH TALENT
    # =====================================================

    "search_talent_description":
        "Find candidates using artificial intelligence and skills-based search.",

    "search_button": "Search",
    "skills_found": "Skills Found",
    "missing_skills": "Missing Skills",
    "no_talent_found": "No talent found.",

    "talent_pool_description":
        "AI-powered talent database designed to help recruiters find, organize and manage professionals faster.",

    "upload_resumes_description":
        "Upload one or multiple resumes and let TalentAI organize everything automatically.",

    # =====================================================
    # CONSULTANT 360
    # =====================================================

    "consultant_360": "Consultant 360°",
    "location_not_informed": "Location not informed",
    "new_status": "New",
    "view_original_resume": "View Original Resume",

    "current_match": "Current Match",
    "availability": "Availability",
    "candidate_rate": "Candidate Rate",
    "stage": "Stage",
    "not_informed_feminine": "Not informed",
    "not_informed": "Not informed",
    "mapped": "Mapped",

    "talia_intelligence": "TALIA Intelligence",
    "executive_summary": "Executive Summary",
    "professional_summary_unavailable": "Professional summary not available.",
    "main_competencies": "Main Competencies",
    "competencies_not_identified": "Competencies not yet identified.",

    "consultant_journal": "Consultant Journal",
    "consultant_journal_description":
        "Record candidate interactions, notes and history.",
    "new_note": "New Note",
    "type": "Type",
    "note_observation": "Observation",
    "note_call": "Call",
    "note_interview": "Interview",
    "note_client": "Client",
    "note_negotiation": "Negotiation",
    "note_placeholder": "Enter your note...",
    "save_note": "Save Note",
    "no_notes": "No notes registered.",

    "experience": "Experience",
    "english": "English",
    "spanish": "Spanish",

    "commercial": "Commercial",
    "edit_commercial": "Edit Commercial",
    "contract_type": "Contract Type",
    "work_model": "Work Model",
    "current_client": "Current Client",
    "current_project": "Current Project",
    "client_rate": "Client Rate",

    "back_to_talent_pool": "Back to Talent Pool",

    # =====================================================
    # JOB DETAIL / RECRUITMENT WORKSPACE
    # =====================================================

    "candidates_sent_successfully": "Candidates sent successfully!",
    "close_job": "Close Job",
    "edit_job": "Edit Job",
    "update_job": "Update Job",
    "job_description": "Description",
    "analyze_resumes_ai": "Analyze Resumes with AI",

    "candidate_ranking": "Candidate Ranking",
    "total": "Total",
    "sent": "Sent",
    "client": "Client",

    "email_language": "Email language",
    "portuguese": "Portuguese",

    "top_candidate": "Top",
    "pdf_without_text": "PDF without text",

    "stage_mapped": "Mapped",
    "stage_contact": "Contact",
    "stage_interview": "Interview",
    "stage_client": "Client",
    "stage_approved": "Approved",
    "stage_rejected": "Rejected",

    "summary": "Summary",
    "no_summary": "No summary",
    "skills_found_label": "Skills found",
    "missing_skills_label": "Missing skills",
    "not_found": "Not found",

    "generate_email_selected": "Generate email for selected candidates",
    "back": "Back",

    # =====================================================
    # SUBMISSION HISTORY
    # =====================================================

    "submission_history": "Submission History",
    "submission_history_description":
        "Track candidates submitted to clients.",
    "submitted_candidates": "Submitted Candidates",
    "no_submissions_yet": "No submissions yet.",

    # =====================================================
    # CLIENTS
    # =====================================================

    "contact_name": "Contact name",
    "company": "Company",
    "save_client": "Save client",
    "client_list": "Client list",
    "view_jobs": "View jobs",

    "back_to_clients": "Back to Clients",
    "client_jobs": "Jobs linked to this client",
    "contact": "Contact",
    "linked_jobs": "linked job(s)",
    "open_job": "Open Job",
    "no_linked_jobs": "No linked jobs",
    "no_client_jobs": "This client does not have any jobs yet.",

    # =====================================================
    # FILE UPLOAD
    # =====================================================

    "choose_files": "Choose files",
    "no_files_selected": "No files selected",
    "files_selected": "files selected",

    # =====================================================
    # TALENTAI CAREERS
    # =====================================================

    "careers_open_opportunities": "Open Opportunities",
    "careers_badge": "TALENTAI CAREERS",
    "careers_hero_title": "Find your next",
    "careers_hero_highlight": "opportunity.",
    "careers_hero_description":
        "Discover opportunities that match your experience, skills and career goals.",
    "careers_section_title": "Open Opportunities",
    "careers_section_description":
        "Explore our current opportunities and find your next challenge.",
    "careers_search_placeholder": "Search opportunities...",
    "careers_open_status": "Open",
    "careers_view_opportunity": "View Opportunity",
    "view_public_job": "View Public Job",
    "copy_public_link": "Copy Public Link",
    "careers_no_opportunities":
        "There are no open opportunities at this time.",
    "careers_footer": "Talent Intelligence Platform",

    # =====================================================
    # CAREERS - JOB DETAIL
    # =====================================================

    "career_back_opportunities": "Back to opportunities",
    "career_job_opportunity": "OPPORTUNITY",
    "career_job_description": "About the opportunity",
    "career_job_client": "Company",
    "career_job_status": "Status",
    "career_job_open": "Open",
    "career_apply": "Apply for this position",
    "career_apply_description":
        "Submit your profile and join our talent network.",

    # =====================================================
    # CAREERS - APPLICATION
    # =====================================================

    "career_apply_title": "Apply for this opportunity",
    "career_apply_subtitle":
        "Submit your information and resume to our Talent Acquisition team.",
    "career_full_name": "Full name",
    "career_email": "Email",
    "career_phone": "Phone",
    "career_resume": "Resume",
    "career_choose_resume": "Choose resume",
    "career_resume_help": "Upload your resume in PDF format.",
    "career_submit_application": "Submit application",
    "career_back_job": "Back to opportunity",
    "career_required_fields": "All fields marked with * are required.",

    # =====================================================
    # CAREERS - APPLICATION SUBMITTED
    # =====================================================

    "career_success_badge": "APPLICATION RECEIVED",
    "career_success_title": "Application submitted successfully!",
    "career_success_message":
        "We received your resume and your profile is now part of our evaluation process.",
    "career_success_job": "Opportunity",
    "career_success_next":
        "Our Talent Acquisition team may contact you if your profile moves forward in the process.",
    "career_success_back": "View other opportunities",

}