"""estrutura inicial TalentAI

Revision ID: 1e06834096f7
Revises: 
Create Date: 2026-07-13 19:37:35.414730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e06834096f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatos', sa.Column('data_disponibilidade', sa.DateTime(), nullable=True))
    op.add_column('candidatos', sa.Column('modelo_contratacao', sa.String(), nullable=True))
    op.add_column('candidatos', sa.Column('modelo_trabalho', sa.String(), nullable=True))
    op.add_column('candidatos', sa.Column('cliente_atual', sa.String(), nullable=True))
    op.add_column('candidatos', sa.Column('projeto_atual', sa.String(), nullable=True))
    op.add_column('candidatos', sa.Column('interesse_oportunidades', sa.Boolean(), nullable=True))
    op.add_column('candidatos', sa.Column('ultimo_contato', sa.DateTime(), nullable=True))
    op.add_column('candidatos', sa.Column('proximo_followup', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidatos', 'proximo_followup')
    op.drop_column('candidatos', 'ultimo_contato')
    op.drop_column('candidatos', 'interesse_oportunidades')
    op.drop_column('candidatos', 'projeto_atual')
    op.drop_column('candidatos', 'cliente_atual')
    op.drop_column('candidatos', 'modelo_trabalho')
    op.drop_column('candidatos', 'modelo_contratacao')
    op.drop_column('candidatos', 'data_disponibilidade')
    # ### end Alembic commands ###
